@startuml pop
start
:Uszereguj lekcje według rosnącej liczby możliwych bloków;
repeat
    :Przypisz kolejną lekcję do pierwszego możliwego bloku;
repeat while (Wszystkie lekcje przypisane do bloków?) is (nie) not (tak)
:Dopisz rozwiązanie do populacji;
repeat
    :Zmutuj pierwsze rozwiązanie i dopisz do populacji;
repeat while (Populacja jest pełna?) is (nie) not (tak)
:Uszereguj populację według oceny rozwiązania;
:Zwróć populację;
end
@enduml